-- MySQL Script generated by MySQL Workbench
-- Tue Apr  9 23:07:16 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WebDiP2018x057
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WebDiP2018x057
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WebDiP2018x057` DEFAULT CHARACTER SET utf8 ;
USE `WebDiP2018x057` ;

-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`Uloge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`Uloge` (
  `idUloge` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUloge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`korisnik` (
  `idkorisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `email` TEXT NOT NULL,
  `datum_vrijeme_uvjeta` DATETIME NULL,
  `Uloge_idUloge` INT NOT NULL,
  PRIMARY KEY (`idkorisnik`),
  INDEX `fk_korisnik_Uloge_idx` (`Uloge_idUloge` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_Uloge`
    FOREIGN KEY (`Uloge_idUloge`)
    REFERENCES `WebDiP2018x057`.`Uloge` (`idUloge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`kategorija_licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`kategorija_licence` (
  `idkategorija_licence` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkategorija_licence`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`licence` (
  `idlicence` INT NOT NULL AUTO_INCREMENT,
  `kategorija` VARCHAR(45) NOT NULL,
  `naziv` VARCHAR(45) NOT NULL,
  `opis` TEXT NOT NULL,
  `slika` TEXT NOT NULL,
  `kategorija_licence_idkategorija_licence` INT NOT NULL,
  PRIMARY KEY (`idlicence`),
  INDEX `fk_licence_kategorija_licence1_idx` (`kategorija_licence_idkategorija_licence` ASC) VISIBLE,
  CONSTRAINT `fk_licence_kategorija_licence1`
    FOREIGN KEY (`kategorija_licence_idkategorija_licence`)
    REFERENCES `WebDiP2018x057`.`kategorija_licence` (`idkategorija_licence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`zahtjevi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`zahtjevi` (
  `idzahtjevi` INT NOT NULL AUTO_INCREMENT,
  `količina` INT NOT NULL,
  `iznos` DECIMAL NOT NULL,
  `datum` DATE NOT NULL,
  `korisnik_idkorisnik1` INT NOT NULL,
  `kategorija_licence_idkategorija_licence1` INT NOT NULL,
  PRIMARY KEY (`idzahtjevi`),
  INDEX `fk_zahtjevi_korisnik1_idx` (`korisnik_idkorisnik1` ASC) VISIBLE,
  INDEX `fk_zahtjevi_kategorija_licence1_idx` (`kategorija_licence_idkategorija_licence1` ASC) VISIBLE,
  CONSTRAINT `fk_zahtjevi_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik1`)
    REFERENCES `WebDiP2018x057`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zahtjevi_kategorija_licence1`
    FOREIGN KEY (`kategorija_licence_idkategorija_licence1`)
    REFERENCES `WebDiP2018x057`.`kategorija_licence` (`idkategorija_licence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`korisnik_ima_licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`korisnik_ima_licence` (
  `datum` DATE NOT NULL,
  `vrijeme` TIME NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  `licence_idlicence` INT NOT NULL,
  INDEX `fk_korisnik_has_licence_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  INDEX `fk_korisnik_has_licence_licence1_idx` (`licence_idlicence` ASC) VISIBLE,
  CONSTRAINT `fk_korisnik_has_licence_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2018x057`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_has_licence_licence1`
    FOREIGN KEY (`licence_idlicence`)
    REFERENCES `WebDiP2018x057`.`licence` (`idlicence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`Administrator_odobrava_zahtjev`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`Administrator_odobrava_zahtjev` (
  `status` VARCHAR(45) NOT NULL,
  `Vrijeme_obrade` DATETIME NOT NULL,
  `zahtjevi_idzahtjevi` INT NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  INDEX `fk_Administrator_odobrava_zahtjev_zahtjevi1_idx` (`zahtjevi_idzahtjevi` ASC) VISIBLE,
  INDEX `fk_Administrator_odobrava_zahtjev_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  CONSTRAINT `fk_Administrator_odobrava_zahtjev_zahtjevi1`
    FOREIGN KEY (`zahtjevi_idzahtjevi`)
    REFERENCES `WebDiP2018x057`.`zahtjevi` (`idzahtjevi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Administrator_odobrava_zahtjev_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2018x057`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`dnevnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`dnevnik` (
  `id_korisnika` INT NULL,
  `kor_ime` VARCHAR(45) NULL,
  `datum` DATE NULL,
  `tip` TEXT NULL,
  `upit` TEXT NULL,
  `radnja` TEXT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`moderator_kategorije`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`moderator_kategorije` (
  `korisnik_idkorisnik` INT NOT NULL,
  `kategorija_licence_idkategorija_licence` INT NOT NULL,
  INDEX `fk_moderator_kategorije_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  INDEX `fk_moderator_kategorije_kategorija_licence1_idx` (`kategorija_licence_idkategorija_licence` ASC) VISIBLE,
  CONSTRAINT `fk_moderator_kategorije_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2018x057`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moderator_kategorije_kategorija_licence1`
    FOREIGN KEY (`kategorija_licence_idkategorija_licence`)
    REFERENCES `WebDiP2018x057`.`kategorija_licence` (`idkategorija_licence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`trgovina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`trgovina` (
  `idtrgovina` INT NOT NULL,
  `naziv` VARCHAR(45) NULL,
  `adresa` VARCHAR(45) NULL,
  `grad` VARCHAR(45) NULL,
  `država` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefon` VARCHAR(45) NULL,
  `web_stranica` VARCHAR(45) NULL,
  PRIMARY KEY (`idtrgovina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`moderator_kupnja_licence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`moderator_kupnja_licence` (
  `količina` INT NOT NULL,
  `iznos` DOUBLE NOT NULL,
  `datum_valjanosti` DATE NOT NULL,
  `korisnik_idkorisnik` INT NOT NULL,
  `licence_idlicence` INT NOT NULL,
  INDEX `fk_moderator_kupnja_licence_korisnik1_idx` (`korisnik_idkorisnik` ASC) VISIBLE,
  INDEX `fk_moderator_kupnja_licence_licence1_idx` (`licence_idlicence` ASC) VISIBLE,
  CONSTRAINT `fk_moderator_kupnja_licence_korisnik1`
    FOREIGN KEY (`korisnik_idkorisnik`)
    REFERENCES `WebDiP2018x057`.`korisnik` (`idkorisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_moderator_kupnja_licence_licence1`
    FOREIGN KEY (`licence_idlicence`)
    REFERENCES `WebDiP2018x057`.`licence` (`idlicence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WebDiP2018x057`.`licence_ima_trgovina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WebDiP2018x057`.`licence_ima_trgovina` (
  `licence_idlicence` INT NOT NULL,
  `trgovina_idtrgovina` INT NOT NULL,
  INDEX `fk_licence_has_trgovina_licence1_idx` (`licence_idlicence` ASC) VISIBLE,
  INDEX `fk_licence_has_trgovina_trgovina1_idx` (`trgovina_idtrgovina` ASC) VISIBLE,
  CONSTRAINT `fk_licence_has_trgovina_licence1`
    FOREIGN KEY (`licence_idlicence`)
    REFERENCES `WebDiP2018x057`.`licence` (`idlicence`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_licence_has_trgovina_trgovina1`
    FOREIGN KEY (`trgovina_idtrgovina`)
    REFERENCES `WebDiP2018x057`.`trgovina` (`idtrgovina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
